package de.schliweb.makeacopy.utils.layout;

import static org.junit.Assert.*;

import android.graphics.Rect;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;

/**
 * Layout ground truth tests that load generated JSON test data and verify layout structure,
 * zone roles, reading order, and text reconstruction. These tests explicitly target the
 * layout analysis path and do not affect the standard OCR path.
 *
 * <p>Ground truth files are generated by the testdata_generator and placed under
 * {@code src/test/resources/layout_ground_truth/}.
 */
public class LayoutGroundTruthTest {

  private static final Gson GSON = new Gson();

  // ── Helper methods ──────────────────────────────────────────────────────

  private JsonObject loadGroundTruth(String filename) {
    String path = "layout_ground_truth/" + filename;
    InputStream is = getClass().getClassLoader().getResourceAsStream(path);
    assertNotNull("Ground truth file not found: " + path, is);
    return GSON.fromJson(new InputStreamReader(is, StandardCharsets.UTF_8), JsonObject.class);
  }

  private JsonObject getFirstPage(JsonObject gt) {
    JsonArray pages = gt.getAsJsonArray("pages");
    assertNotNull("No pages in ground truth", pages);
    assertTrue("Pages array is empty", pages.size() > 0);
    return pages.get(0).getAsJsonObject();
  }

  private JsonArray getZones(JsonObject page) {
    return page.getAsJsonArray("zones");
  }

  private List<String> getStringList(JsonObject obj, String key) {
    JsonArray arr = obj.getAsJsonArray(key);
    List<String> result = new ArrayList<>();
    if (arr != null) {
      for (JsonElement e : arr) {
        result.add(e.getAsString());
      }
    }
    return result;
  }

  private String getZoneRole(JsonArray zones, int index) {
    return zones.get(index).getAsJsonObject().get("role").getAsString();
  }

  private String getZoneId(JsonArray zones, int index) {
    return zones.get(index).getAsJsonObject().get("zone_id").getAsString();
  }

  private String getZoneText(JsonArray zones, int index) {
    return zones.get(index).getAsJsonObject().get("text").getAsString();
  }

  private boolean getZoneIsTextual(JsonArray zones, int index) {
    return zones.get(index).getAsJsonObject().get("is_textual").getAsBoolean();
  }

  private int getZoneLineCount(JsonArray zones, int index) {
    return zones.get(index).getAsJsonObject().getAsJsonArray("lines").size();
  }

  private String reconstructFullText(JsonObject page) {
    return page.get("full_text").getAsString();
  }

  /**
   * Verifies that bounding boxes have valid geometry (x0 < x1, y0 < y1 in PDF coords
   * where y0 can be less than y1 for bottom-left origin).
   */
  private void assertValidBBox(JsonArray bbox, String context) {
    assertNotNull("BBox is null for " + context, bbox);
    assertEquals("BBox must have 4 elements for " + context, 4, bbox.size());
    double x0 = bbox.get(0).getAsDouble();
    double x1 = bbox.get(2).getAsDouble();
    assertTrue("BBox x0 must be < x1 for " + context, x0 < x1);
  }

  // ── Single column (baseline) ────────────────────────────────────────────

  @Test
  public void singleColumn_hasExpectedZoneCount() {
    JsonObject gt = loadGroundTruth("single_column_s42.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(3, zones.size()); // heading + 2 paragraphs
  }

  @Test
  public void singleColumn_firstZoneIsHeading() {
    JsonObject gt = loadGroundTruth("single_column_s42.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals("full_width_heading", getZoneRole(zones, 0));
  }

  @Test
  public void singleColumn_zoneOrderMatchesExpected() {
    JsonObject gt = loadGroundTruth("single_column_s42.json");
    JsonObject page = getFirstPage(gt);
    List<String> expectedOrder = getStringList(page, "expected_zone_order");
    JsonArray zones = getZones(page);
    List<String> actualOrder = new ArrayList<>();
    for (int i = 0; i < zones.size(); i++) {
      actualOrder.add(getZoneId(zones, i));
    }
    assertEquals(expectedOrder, actualOrder);
  }

  @Test
  public void singleColumn_fullTextNotEmpty() {
    JsonObject gt = loadGroundTruth("single_column_s42.json");
    JsonObject page = getFirstPage(gt);
    String fullText = reconstructFullText(page);
    assertFalse("Full text should not be empty", fullText.isEmpty());
  }

  // ── Two-column ──────────────────────────────────────────────────────────

  @Test
  public void twoColumn_hasHeadingAndTwoColumns() {
    JsonObject gt = loadGroundTruth("two_column_s43.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(3, zones.size());
    assertEquals("full_width_heading", getZoneRole(zones, 0));
    assertEquals("paragraph", getZoneRole(zones, 1));
    assertEquals("paragraph", getZoneRole(zones, 2));
  }

  @Test
  public void twoColumn_columnsHaveCorrectIndices() {
    JsonObject gt = loadGroundTruth("two_column_s43.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    JsonObject col0 = zones.get(1).getAsJsonObject();
    JsonObject col1 = zones.get(2).getAsJsonObject();
    assertEquals(0, col0.get("column_index").getAsInt());
    assertEquals(1, col1.get("column_index").getAsInt());
  }

  @Test
  public void twoColumn_headingSpansBothColumns() {
    JsonObject gt = loadGroundTruth("two_column_s43.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    JsonObject heading = zones.get(0).getAsJsonObject();
    assertEquals(2, heading.get("column_span").getAsInt());
  }

  // ── Two-column with sidebar (new) ──────────────────────────────────────

  @Test
  public void twoColSidebar_hasExpectedZoneCount() {
    JsonObject gt = loadGroundTruth("twocol_sidebar_s56.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(4, zones.size()); // heading + 2 cols + sidebar
  }

  @Test
  public void twoColSidebar_rolesAreCorrect() {
    JsonObject gt = loadGroundTruth("twocol_sidebar_s56.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals("full_width_heading", getZoneRole(zones, 0));
    assertEquals("paragraph", getZoneRole(zones, 1));
    assertEquals("paragraph", getZoneRole(zones, 2));
    assertEquals("sidebar", getZoneRole(zones, 3));
  }

  @Test
  public void twoColSidebar_zoneOrderMatchesExpected() {
    JsonObject gt = loadGroundTruth("twocol_sidebar_s56.json");
    JsonObject page = getFirstPage(gt);
    List<String> expectedOrder = getStringList(page, "expected_zone_order");
    JsonArray zones = getZones(page);
    List<String> actualOrder = new ArrayList<>();
    for (int i = 0; i < zones.size(); i++) {
      actualOrder.add(getZoneId(zones, i));
    }
    assertEquals(expectedOrder, actualOrder);
  }

  @Test
  public void twoColSidebar_lineOrderMatchesExpected() {
    JsonObject gt = loadGroundTruth("twocol_sidebar_s56.json");
    JsonObject page = getFirstPage(gt);
    List<String> expectedLineOrder = getStringList(page, "expected_line_order");
    assertFalse("Expected line order should not be empty", expectedLineOrder.isEmpty());
    // Verify all line IDs are unique
    assertEquals(expectedLineOrder.size(),
        expectedLineOrder.stream().distinct().count());
  }

  @Test
  public void twoColSidebar_allZonesHaveValidBBox() {
    JsonObject gt = loadGroundTruth("twocol_sidebar_s56.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    for (int i = 0; i < zones.size(); i++) {
      JsonObject zone = zones.get(i).getAsJsonObject();
      assertValidBBox(zone.getAsJsonArray("bbox"), "zone " + zone.get("zone_id").getAsString());
    }
  }

  // ── Heading + paragraph + separator (new) ──────────────────────────────

  @Test
  public void headingParaSep_hasExpectedStructure() {
    JsonObject gt = loadGroundTruth("heading_para_sep_s57.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(4, zones.size()); // heading + para + separator + para
    assertEquals("full_width_heading", getZoneRole(zones, 0));
    assertEquals("paragraph", getZoneRole(zones, 1));
    assertEquals("separator", getZoneRole(zones, 2));
    assertEquals("paragraph", getZoneRole(zones, 3));
  }

  @Test
  public void headingParaSep_separatorIsNotTextual() {
    JsonObject gt = loadGroundTruth("heading_para_sep_s57.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertFalse("Separator should not be textual", getZoneIsTextual(zones, 2));
    assertEquals("Separator should have empty text", "", getZoneText(zones, 2));
  }

  @Test
  public void headingParaSep_separatorHasNoLines() {
    JsonObject gt = loadGroundTruth("heading_para_sep_s57.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(0, getZoneLineCount(zones, 2));
  }

  @Test
  public void headingParaSep_readingOrderIsTopToBottom() {
    JsonObject gt = loadGroundTruth("heading_para_sep_s57.json");
    JsonObject page = getFirstPage(gt);
    List<String> order = getStringList(page, "expected_zone_order");
    assertEquals(List.of("z0", "z1", "z2", "z3"), order);
  }

  // ── Asymmetric short right column (new) ────────────────────────────────

  @Test
  public void asymmetricShortRight_hasThreeZones() {
    JsonObject gt = loadGroundTruth("asymmetric_short_right_s58.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(3, zones.size()); // heading + left col + right col
  }

  @Test
  public void asymmetricShortRight_leftColumnHasMoreLines() {
    JsonObject gt = loadGroundTruth("asymmetric_short_right_s58.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    int leftLines = getZoneLineCount(zones, 1);
    int rightLines = getZoneLineCount(zones, 2);
    assertTrue("Left column should have more lines than right",
        leftLines > rightLines);
  }

  @Test
  public void asymmetricShortRight_headingBeforeColumns() {
    JsonObject gt = loadGroundTruth("asymmetric_short_right_s58.json");
    JsonObject page = getFirstPage(gt);
    List<String> order = getStringList(page, "expected_zone_order");
    assertEquals("z0", order.get(0)); // heading first
  }

  // ── Simple invoice (new) ───────────────────────────────────────────────

  @Test
  public void simpleInvoice_hasHeadingParaAndTable() {
    JsonObject gt = loadGroundTruth("simple_invoice_s59.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(3, zones.size());
    assertEquals("heading", getZoneRole(zones, 0));
    assertEquals("paragraph", getZoneRole(zones, 1));
    assertEquals("table_like", getZoneRole(zones, 2));
  }

  @Test
  public void simpleInvoice_tableLikeHasMultipleRows() {
    JsonObject gt = loadGroundTruth("simple_invoice_s59.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    int tableLines = getZoneLineCount(zones, 2);
    assertTrue("Table should have at least 2 rows", tableLines >= 2);
  }

  @Test
  public void simpleInvoice_allZonesAreTextual() {
    JsonObject gt = loadGroundTruth("simple_invoice_s59.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    for (int i = 0; i < zones.size(); i++) {
      assertTrue("Zone " + i + " should be textual", getZoneIsTextual(zones, i));
    }
  }

  // ── List after text (new) ──────────────────────────────────────────────

  @Test
  public void listAfterText_hasCorrectRoleSequence() {
    JsonObject gt = loadGroundTruth("list_after_text_s60.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(4, zones.size());
    assertEquals("heading", getZoneRole(zones, 0));
    assertEquals("paragraph", getZoneRole(zones, 1));
    assertEquals("list", getZoneRole(zones, 2));
    assertEquals("paragraph", getZoneRole(zones, 3));
  }

  @Test
  public void listAfterText_listHasBulletItems() {
    JsonObject gt = loadGroundTruth("list_after_text_s60.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    JsonObject listZone = zones.get(2).getAsJsonObject();
    String text = listZone.get("text").getAsString();
    assertTrue("List text should contain bullet markers", text.contains("•"));
  }

  @Test
  public void listAfterText_readingOrderPreservesListPosition() {
    JsonObject gt = loadGroundTruth("list_after_text_s60.json");
    JsonObject page = getFirstPage(gt);
    List<String> order = getStringList(page, "expected_zone_order");
    // List (z2) must come after paragraph (z1) and before closing paragraph (z3)
    int listIdx = order.indexOf("z2");
    int paraBeforeIdx = order.indexOf("z1");
    int paraAfterIdx = order.indexOf("z3");
    assertTrue(listIdx > paraBeforeIdx);
    assertTrue(listIdx < paraAfterIdx);
  }

  // ── Disturbing block (new) ─────────────────────────────────────────────

  @Test
  public void disturbingBlock_hasSidebarHeadingAndParagraph() {
    JsonObject gt = loadGroundTruth("disturbing_block_s61.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    assertEquals(3, zones.size());
    assertEquals("sidebar", getZoneRole(zones, 0));
    assertEquals("full_width_heading", getZoneRole(zones, 1));
    assertEquals("paragraph", getZoneRole(zones, 2));
  }

  @Test
  public void disturbingBlock_sidebarDoesNotCorruptMainText() {
    JsonObject gt = loadGroundTruth("disturbing_block_s61.json");
    JsonObject page = getFirstPage(gt);
    JsonArray zones = getZones(page);
    // Main heading text should be intact
    String headingText = getZoneText(zones, 1);
    assertTrue(headingText.contains("Hauptdokument"));
    // Main paragraph should have substantial text
    String paraText = getZoneText(zones, 2);
    assertTrue("Main paragraph should have content", paraText.length() > 50);
  }

  @Test
  public void disturbingBlock_fullTextContainsAllZones() {
    JsonObject gt = loadGroundTruth("disturbing_block_s61.json");
    JsonObject page = getFirstPage(gt);
    String fullText = reconstructFullText(page);
    assertTrue(fullText.contains("Ref: 2024-0042"));
    assertTrue(fullText.contains("Hauptdokument"));
  }

  // ── ReadingOrderSorter integration with ground truth ───────────────────

  @Test
  public void readingOrderSorter_twoColumnRegions_sortedLeftToRight() {
    // Build DocumentRegion objects mimicking two-column ground truth
    Rect leftBounds = new Rect();
    leftBounds.left = 40;
    leftBounds.top = 100;
    leftBounds.right = 280;
    leftBounds.bottom = 400;

    Rect rightBounds = new Rect();
    rightBounds.left = 300;
    rightBounds.top = 100;
    rightBounds.right = 555;
    rightBounds.bottom = 400;

    DocumentRegion leftCol = new DocumentRegion(leftBounds, DocumentRegion.Type.COLUMN);
    leftCol.setColumnIndex(0);
    DocumentRegion rightCol = new DocumentRegion(rightBounds, DocumentRegion.Type.COLUMN);
    rightCol.setColumnIndex(1);

    List<DocumentRegion> regions = new ArrayList<>();
    regions.add(rightCol); // add right first to test sorting
    regions.add(leftCol);

    ReadingOrderSorter.sortByColumns(regions, ReadingOrderSorter.TextDirection.LTR);

    assertEquals(0, regions.get(0).getReadingOrder());
    assertEquals(1, regions.get(1).getReadingOrder());
  }

  @Test
  public void readingOrderSorter_headerBeforeBody() {
    DocumentRegion header = new DocumentRegion(null, DocumentRegion.Type.HEADER);
    DocumentRegion body = new DocumentRegion(null, DocumentRegion.Type.BODY);
    DocumentRegion footer = new DocumentRegion(null, DocumentRegion.Type.FOOTER);

    List<DocumentRegion> regions = new ArrayList<>();
    regions.add(footer);
    regions.add(body);
    regions.add(header);

    ReadingOrderSorter.sortHierarchical(regions, ReadingOrderSorter.TextDirection.LTR);

    assertEquals(DocumentRegion.Type.HEADER, regions.get(0).getType());
    assertEquals(DocumentRegion.Type.BODY, regions.get(1).getType());
    assertEquals(DocumentRegion.Type.FOOTER, regions.get(2).getType());
  }

  // ── Cross-cutting: all ground truth files have consistent structure ────

  @Test
  public void allGroundTruthFiles_haveConsistentStructure() {
    String[] files = {
        "single_column_s42.json",
        "two_column_s43.json",
        "twocol_sidebar_s56.json",
        "heading_para_sep_s57.json",
        "asymmetric_short_right_s58.json",
        "simple_invoice_s59.json",
        "list_after_text_s60.json",
        "disturbing_block_s61.json",
    };
    for (String file : files) {
      JsonObject gt = loadGroundTruth(file);
      assertNotNull(file + ": missing filename", gt.get("filename"));
      assertNotNull(file + ": missing description", gt.get("description"));
      assertNotNull(file + ": missing difficulty", gt.get("difficulty"));
      assertNotNull(file + ": missing seed", gt.get("seed"));

      JsonObject page = getFirstPage(gt);
      assertNotNull(file + ": missing width_pt", page.get("width_pt"));
      assertNotNull(file + ": missing height_pt", page.get("height_pt"));
      assertNotNull(file + ": missing expected_zone_order", page.get("expected_zone_order"));
      assertNotNull(file + ": missing expected_line_order", page.get("expected_line_order"));
      assertNotNull(file + ": missing coordinate_system", page.get("coordinate_system"));

      JsonArray zones = getZones(page);
      assertTrue(file + ": should have at least one zone", zones.size() > 0);

      for (int i = 0; i < zones.size(); i++) {
        JsonObject zone = zones.get(i).getAsJsonObject();
        assertNotNull(file + " zone " + i + ": missing zone_id", zone.get("zone_id"));
        assertNotNull(file + " zone " + i + ": missing role", zone.get("role"));
        assertNotNull(file + " zone " + i + ": missing bbox", zone.get("bbox"));
        assertNotNull(file + " zone " + i + ": missing is_textual", zone.get("is_textual"));
      }
    }
  }

  @Test
  public void allGroundTruthFiles_lineIdsAreUniquePerPage() {
    String[] files = {
        "twocol_sidebar_s56.json",
        "heading_para_sep_s57.json",
        "asymmetric_short_right_s58.json",
        "simple_invoice_s59.json",
        "list_after_text_s60.json",
        "disturbing_block_s61.json",
    };
    for (String file : files) {
      JsonObject gt = loadGroundTruth(file);
      JsonObject page = getFirstPage(gt);
      List<String> lineOrder = getStringList(page, "expected_line_order");
      long uniqueCount = lineOrder.stream().distinct().count();
      assertEquals(file + ": duplicate line IDs found",
          lineOrder.size(), uniqueCount);
    }
  }
}
