#!/usr/bin/env bash
set -euo pipefail

# Enable shell tracing when DEBUG/TRACE is set
if [ "${DEBUG:-0}" = "1" ] || [ "${TRACE:-0}" = "1" ]; then
  set -x
fi

# Quiet mode default: reduce console output. Set VERBOSE=1 for detailed logs.
VERBOSE="${VERBOSE:-0}"
info() {
  if [ "$VERBOSE" = "1" ]; then
    echo "$@"
  else
    >&2 echo "$@"
  fi
}

# ===============================
# Reproducible build timestamp
# ===============================
export SOURCE_DATE_EPOCH=1700000000
export TZ=UTC

# ===============================
# Repo/paths
# ===============================
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ORT_DIR_ORIG="$REPO_DIR/external/onnxruntime"   # submodule (e.g., v1.24.1)
ORT_DIR="/tmp/onnxruntime-src"
JNI_LIBS_BASE="$REPO_DIR/app/src/main/jniLibs"
APP_LIBS="$REPO_DIR/app/libs"
BUILD_ROOT="/tmp/onnxruntime-build"

# Minimal build with reduced operator config
# Two configs ship in the repo:
#   * DocQuad      (always required)         -> docquadnet256_trained_opset17.required_operators.config
#   * PaddleOCR v5 (only for `paddle` flavor)-> paddleocr_v5.required_operators.config
# By default both are merged into a single config under /tmp/ for path-neutral,
# reproducible builds across environments.
#
# Overrides:
#   ORT_OPS_CONFIG=<path>     -> use exactly that single config file (no merge).
#   ORT_OPS_CONFIG=none       -> disable minimal build entirely.
#   ORT_OPS_CONFIGS=a:b:c     -> explicit colon-separated list of configs to merge.
#   INCLUDE_PADDLE_OPS=0      -> exclude the PaddleOCR config from the default merge.
#   INCLUDE_PADDLE_V6_OPS=1   -> additionally merge the experimental PaddleOCR v6
#                                (small) config into the default merge. Default 0
#                                so existing (v5-only) builds remain unchanged.
REPO_OPS_CONFIG_DOCQUAD="$REPO_DIR/app/src/main/assets/docquad/docquadnet256_trained_opset17.required_operators.config"
REPO_OPS_CONFIG_PADDLE="$REPO_DIR/app/src/paddle/assets/paddleocr/v5/paddleocr_v5.required_operators.config"
REPO_OPS_CONFIG_PADDLE_V6="$REPO_DIR/app/src/paddle/assets/paddleocr/v6/paddleocr_v6_small.required_operators.config"
ORT_OPS_CONFIG="${ORT_OPS_CONFIG:-}"
ORT_OPS_CONFIGS="${ORT_OPS_CONFIGS:-}"
INCLUDE_PADDLE_OPS="${INCLUDE_PADDLE_OPS:-1}"
INCLUDE_PADDLE_V6_OPS="${INCLUDE_PADDLE_V6_OPS:-0}"

# Merge multiple "domain;opset;OpA,OpB" config files into one.  Lines with the
# same domain+opset are unioned; comments are dropped and replaced with a small
# provenance header.  The implementation is `awk`-only to keep the script
# free of additional Python deps.
merge_ops_configs() {
  local out="$1"; shift
  {
    echo "# Generated by scripts/build_onnxruntime_android.sh (merged)"
    for f in "$@"; do
      echo "# - $f"
    done
    awk -F';' '
      /^[[:space:]]*#/ { next }
      NF < 3            { next }
      {
        key = $1 ";" $2
        n = split($3, ops, ",")
        for (i = 1; i <= n; i++) {
          op = ops[i]
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", op)
          if (op != "") seen[key, op] = 1
          if (!(key in keys)) { keys[key] = 1; order[++count] = key }
        }
      }
      END {
        for (i = 1; i <= count; i++) {
          key = order[i]
          first = 1
          line = ""
          # collect ops for this key in sorted order
          delete arr
          m = 0
          for (k in seen) {
            split(k, parts, SUBSEP)
            if (parts[1] == key) arr[++m] = parts[2]
          }
          # simple insertion sort
          for (a = 2; a <= m; a++) {
            x = arr[a]; b = a - 1
            while (b >= 1 && arr[b] > x) { arr[b+1] = arr[b]; b-- }
            arr[b+1] = x
          }
          for (a = 1; a <= m; a++) {
            line = (first ? arr[a] : line "," arr[a])
            first = 0
          }
          print key ";" line
        }
      }
    ' "$@"
  } > "$out"
}

if [ "$ORT_OPS_CONFIG" = "none" ]; then
  ORT_OPS_CONFIG=""
  info "Minimal build: disabled (ORT_OPS_CONFIG=none)"
elif [ -n "$ORT_OPS_CONFIG" ]; then
  # Explicit single-file override from environment.
  if [ ! -f "$ORT_OPS_CONFIG" ]; then
    echo "ERROR: ORT_OPS_CONFIG file not found: $ORT_OPS_CONFIG" >&2
    exit 1
  fi
  ORT_OPS_CONFIG="$(cd "$(dirname "$ORT_OPS_CONFIG")" && pwd)/$(basename "$ORT_OPS_CONFIG")"
  info "Minimal build: enabled (custom ops config: $ORT_OPS_CONFIG)"
else
  # Build the list of configs to merge.
  CONFIGS_TO_MERGE=()
  if [ -n "$ORT_OPS_CONFIGS" ]; then
    OLD_IFS="$IFS"; IFS=':'
    for f in $ORT_OPS_CONFIGS; do
      [ -n "$f" ] || continue
      if [ ! -f "$f" ]; then
        IFS="$OLD_IFS"
        echo "ERROR: ORT_OPS_CONFIGS entry not found: $f" >&2
        exit 1
      fi
      CONFIGS_TO_MERGE+=("$(cd "$(dirname "$f")" && pwd)/$(basename "$f")")
    done
    IFS="$OLD_IFS"
  else
    [ -f "$REPO_OPS_CONFIG_DOCQUAD" ] && CONFIGS_TO_MERGE+=("$REPO_OPS_CONFIG_DOCQUAD")
    if [ "$INCLUDE_PADDLE_OPS" = "1" ] && [ -f "$REPO_OPS_CONFIG_PADDLE" ]; then
      CONFIGS_TO_MERGE+=("$REPO_OPS_CONFIG_PADDLE")
    fi
    # Experimental PaddleOCR v6 (small) — opt-in only, default off (v5 stays default).
    if [ "$INCLUDE_PADDLE_V6_OPS" = "1" ]; then
      if [ -f "$REPO_OPS_CONFIG_PADDLE_V6" ]; then
        CONFIGS_TO_MERGE+=("$REPO_OPS_CONFIG_PADDLE_V6")
      else
        echo "ERROR: INCLUDE_PADDLE_V6_OPS=1 but config not found: $REPO_OPS_CONFIG_PADDLE_V6" >&2
        exit 1
      fi
    fi
  fi

  if [ "${#CONFIGS_TO_MERGE[@]}" -eq 0 ]; then
    ORT_OPS_CONFIG=""
    info "Minimal build: disabled (no ops config found)"
  elif [ "${#CONFIGS_TO_MERGE[@]}" -eq 1 ]; then
    ORT_OPS_CONFIG="/tmp/ort_required_operators.config"
    cp -f "${CONFIGS_TO_MERGE[0]}" "$ORT_OPS_CONFIG"
    info "Minimal build: enabled (single config: ${CONFIGS_TO_MERGE[0]})"
  else
    ORT_OPS_CONFIG="/tmp/ort_required_operators.config"
    merge_ops_configs "$ORT_OPS_CONFIG" "${CONFIGS_TO_MERGE[@]}"
    info "Minimal build: enabled (merged ${#CONFIGS_TO_MERGE[@]} configs into $ORT_OPS_CONFIG):"
    for f in "${CONFIGS_TO_MERGE[@]}"; do info "  - $f"; done
  fi
fi

# ABIs (extend if needed)
ABIS="${ABIS:-arm64-v8a armeabi-v7a x86 x86_64}"
info "ONNX Runtime ABIs: $ABIS"
info "ENV SUMMARY:"
info "  Host: $(uname -a)"
info "  TZ=$TZ SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"

# ===============================
# Cross-platform CPU jobs
# ===============================
cpu_jobs() {
  # Try POSIX and platform-specific ways; fall back to 1
  getconf _NPROCESSORS_ONLN 2>/dev/null || \
  nproc 2>/dev/null || \
  sysctl -n hw.ncpu 2>/dev/null || \
  echo 1
}
JOBS="$(cpu_jobs)"
export CMAKE_BUILD_PARALLEL_LEVEL="$JOBS"   # CMake/Ninja honor this
info "Parallel jobs: $JOBS"

# ===============================
# Prefer Ninja if available (faster), otherwise fall back
# ===============================
if command -v ninja >/dev/null 2>&1; then
  CMAKE_GENERATOR="Ninja"
  info "CMake generator: Ninja"
else
  CMAKE_GENERATOR=""
  info "CMake generator: Unix Makefiles (ninja not found)"
fi

# ===============================
# Locate SDK/NDK (macOS & Linux)
# ===============================
# Prefer existing env if provided
# SDK root
if [ -z "${ANDROID_SDK_ROOT:-}" ]; then
  if [ -n "${ANDROID_HOME:-}" ] && [ -d "$ANDROID_HOME" ]; then
    export ANDROID_SDK_ROOT="$ANDROID_HOME"
  elif [ -d "$HOME/Library/Android/sdk" ]; then
    export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"         # macOS default
  elif [ -d "$HOME/Android/Sdk" ]; then
    export ANDROID_SDK_ROOT="$HOME/Android/Sdk"                 # Linux default
  fi
fi
info "SDK: ${ANDROID_SDK_ROOT:-UNKNOWN}"

# NDK home
if [ -z "${ANDROID_NDK_HOME:-}" ]; then
  CANDIDATES=()
  [ -n "${ANDROID_SDK_ROOT:-}" ] && CANDIDATES+=("$ANDROID_SDK_ROOT/ndk")
  [ -d "$HOME/Library/Android/sdk/ndk" ] && CANDIDATES+=("$HOME/Library/Android/sdk/ndk")
  [ -d "$HOME/Android/Sdk/ndk" ] && CANDIDATES+=("$HOME/Android/Sdk/ndk")

  for base in "${CANDIDATES[@]}"; do
    if [ -d "$base" ]; then
      LATEST_NDK="$(find "$base" -maxdepth 1 -type d -name "[0-9]*" | sort -Vr | head -n 1 || true)"
      if [ -n "$LATEST_NDK" ]; then
        export ANDROID_NDK_HOME="$LATEST_NDK"
        break
      fi
    fi
  done
fi
[ -z "${ANDROID_NDK_HOME:-}" ] && { echo "ERROR: ANDROID_NDK_HOME not set and no NDK found"; exit 1; }
info "NDK: $ANDROID_NDK_HOME"

# ===============================
# JDK 21 (preferred) / 17 (fallback)
# ===============================
HOST_OS="$(uname | tr '[:upper:]' '[:lower:]')"
if [ "$HOST_OS" = "darwin" ]; then
  set +e
  if /usr/libexec/java_home -v 21 >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 21)"
  elif /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
  fi
  set -e
fi
if [ -n "${JAVA_HOME:-}" ]; then
  export PATH="$JAVA_HOME/bin:$PATH"
  export ORG_GRADLE_JAVA_HOME="$JAVA_HOME"
fi
info "JAVA_HOME: ${JAVA_HOME:-unset}"
java -version >/dev/null 2>&1 || info "WARN: 'java' not found or wrong version (need >= 21)"

# ===============================
# Strip tool (optional)
# ===============================
HOST_TAG="${HOST_OS}-x86_64"
STRIP_BIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$HOST_TAG/bin/llvm-strip"
if [ ! -x "$STRIP_BIN" ]; then
  STRIP_BIN="$(command -v llvm-strip || true)"
fi
[ -x "$STRIP_BIN" ] && info "llvm-strip: $STRIP_BIN" || info "WARN: llvm-strip not found – skipping stripping."

# ===============================
# Clean submodule working tree
# ===============================
pushd "$ORT_DIR_ORIG" >/dev/null
git clean -xfd
git checkout .
popd >/dev/null

# Fresh copy of ONNX Runtime sources into a path that's stable across machines
info "Copying ONNX sources to $ORT_DIR ..."
rm -rf "$ORT_DIR"
mkdir -p "$ORT_DIR"
cp -a "$ORT_DIR_ORIG/." "$ORT_DIR"

# Use pinned build-android.gradle and settings-android.gradle for reproducible Java/AAR builds
PINNED_GRADLE="$REPO_DIR/external/onnxruntime_pinned/build-android.gradle"
PINNED_SETTINGS="$REPO_DIR/external/onnxruntime_pinned/settings-android.gradle"
if [ -f "$PINNED_GRADLE" ]; then
  cp -f "$PINNED_GRADLE" "$ORT_DIR/java/build-android.gradle"
  info "Pinned build-android.gradle applied."
else
  echo "ERROR: Pinned build-android.gradle not found at $PINNED_GRADLE" >&2
  exit 1
fi
if [ -f "$PINNED_SETTINGS" ]; then
  cp -f "$PINNED_SETTINGS" "$ORT_DIR/java/settings-android.gradle"
  info "Pinned settings-android.gradle applied."
else
  echo "ERROR: Pinned settings-android.gradle not found at $PINNED_SETTINGS" >&2
  exit 1
fi

# Use pinned gradle-wrapper.properties for reproducible Gradle version
PINNED_WRAPPER="$REPO_DIR/external/onnxruntime_pinned/gradle-wrapper.properties"
ORT_WRAPPER_PROPS="$ORT_DIR/java/gradle/wrapper/gradle-wrapper.properties"
if [ -f "$PINNED_WRAPPER" ]; then
  cp -f "$PINNED_WRAPPER" "$ORT_WRAPPER_PROPS"
  info "Pinned gradle-wrapper.properties applied."
else
  echo "ERROR: Pinned gradle-wrapper.properties not found at $PINNED_WRAPPER" >&2
  exit 1
fi

# ===============================
# Pick a CMake >= 3.28 ONLY for ONNX Runtime
# (prefer Android SDK; allow override via ORT_CMAKE)
# ===============================
ver_ge() {  # returns 0 if $1 >= $2
  [ "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" = "$2" ]
}

pick_sdk_cmake() {
  local sdk="${ANDROID_SDK_ROOT:-/opt/android-sdk}"
  if [ -d "$sdk/cmake" ]; then
    local cand
    cand=$(find "$sdk/cmake" -maxdepth 1 -type d -name "[0-9]*" | sort -V | tail -n1)
    if [ -n "$cand" ] && [ -x "$cand/bin/cmake" ]; then
      echo "$cand/bin/cmake"
      return 0
    fi
  fi
  return 1
}

if [ -n "${ORT_CMAKE:-}" ] && [ -x "${ORT_CMAKE:-}" ]; then
  CMAKE_PATH="$ORT_CMAKE"
else
  CMAKE_PATH="$(pick_sdk_cmake || true)"
  if [ -z "${CMAKE_PATH:-}" ]; then
    CMAKE_PATH="$(command -v cmake || true)"
  fi
fi

if [ -z "${CMAKE_PATH:-}" ]; then
  echo "ERROR: cmake not found (need >= 3.28 for ONNX Runtime)" >&2
  exit 1
fi

cmv="$("$CMAKE_PATH" --version | awk '/version/{print $3; exit}')"
info "CMake for ORT: $CMAKE_PATH (version $cmv)"
if ! ver_ge "$cmv" "3.28.0"; then
  echo "ERROR: CMake $cmv < 3.28.0 for ONNX Runtime." >&2
  echo "       Install SDK cmake >= 3.28 (e.g. ANDROID_SDK_ROOT/cmake/3.31.x) or set ORT_CMAKE=<path>." >&2
  exit 1
fi

info "SDK: ${ANDROID_SDK_ROOT:-UNKNOWN}"
info "NDK: $ANDROID_NDK_HOME"

# ===============================
# Build per ABI (FULL, XNNPACK+NNAPI, Java)
# ===============================
rm -rf "$BUILD_ROOT"
mkdir -p "$BUILD_ROOT" "$APP_LIBS"

for ABI in $ABIS; do
  info "Building ONNX Runtime for $ABI (XNNPACK+NNAPI)"
  ABI_BUILD_DIR="$BUILD_ROOT/$ABI"
  rm -rf "$ABI_BUILD_DIR"
  mkdir -p "$ABI_BUILD_DIR"

  # Repro/path-neutral flags
  SRC_DIR="$ORT_DIR"
  C_FLAGS="-g0 -fdebug-prefix-map=$SRC_DIR=. -fmacro-prefix-map=$SRC_DIR=. -ffile-prefix-map=$SRC_DIR=."
  CXX_FLAGS="$C_FLAGS"
  LDFLAGS="-Wl,--build-id=none -Wl,-z,max-page-size=16384"

  # Common build.py args
  COMMON_ARGS=(
    --build_dir "$ABI_BUILD_DIR"
    --config Release
    --build_shared_lib
    --skip_tests
    --skip_onnx_tests
    --parallel "$JOBS"
    --use_full_protobuf
    --android
    --android_sdk_path "${ANDROID_SDK_ROOT:?}"
    --android_ndk_path "${ANDROID_NDK_HOME:?}"
    --android_api 29
    --use_xnnpack
    --use_nnapi
    --android_abi "$ABI"
    --build_java
    --skip_submodule_sync
    --compile_no_warning_as_error
  )

  # Minimal build flags (when ORT_OPS_CONFIG is set)
  if [ -n "$ORT_OPS_CONFIG" ]; then
    COMMON_ARGS+=(
      --minimal_build extended
      --include_ops_by_config "$ORT_OPS_CONFIG"
    )
  fi
  # Prefer Ninja if available
  if [ -n "${CMAKE_GENERATOR:-}" ]; then
    COMMON_ARGS+=( --cmake_generator "$CMAKE_GENERATOR" )
  fi

  # CMake defines
  CMAKE_DEFINES=(
    onnxruntime_BUILD_SHARED_LIB=ON
    onnxruntime_BUILD_JAVA=ON
    onnxruntime_ENABLE_PYTHON=OFF
    onnxruntime_BUILD_CSHARP=OFF
    onnxruntime_BUILD_NODEJS=OFF
    onnxruntime_BUILD_OBJC=OFF
    onnxruntime_BUILD_BENCHMARKS=OFF
    onnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF

    onnxruntime_USE_FULL_PROTOBUF=ON
    onnxruntime_USE_MIMALLOC=OFF
    onnxruntime_USE_XNNPACK=ON
    onnxruntime_USE_KLEIDIAI=OFF
    onnxruntime_USE_SVE=OFF
    onnxruntime_USE_CUDA=OFF
    onnxruntime_USE_TENSORRT=OFF
    onnxruntime_USE_ROCM=OFF
    onnxruntime_USE_DNNL=OFF
    onnxruntime_USE_OPENVINO=OFF
    onnxruntime_USE_QNN=OFF
    onnxruntime_USE_ARMNN=OFF
    onnxruntime_USE_ACL=OFF
    onnxruntime_USE_WEBNN=OFF
    onnxruntime_USE_WEBGPU=OFF
    onnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF

    onnxruntime_ENABLE_LTO=OFF
    onnxruntime_ENABLE_MEMORY_PROFILE=OFF
    onnxruntime_ENABLE_LAZY_TENSOR=OFF

    onnxruntime_DISABLE_CONTRIB_OPS=OFF
    onnxruntime_DISABLE_ML_OPS=ON
    onnxruntime_DISABLE_RTTI=ON
    onnxruntime_DISABLE_EXCEPTIONS=ON
    onnxruntime_DISABLE_FLOAT8_TYPES=ON
    onnxruntime_BUILD_SHARED_LIB_TESTS=OFF
    onnxruntime_BUILD_UNIT_TESTS=OFF
    # Optional footprint tweaks:
    # onnxruntime_DISABLE_SPARSE_TENSORS=ON
    # onnxruntime_DISABLE_OPTIONAL_TYPE=ON

    CMAKE_C_FLAGS="$C_FLAGS"
    CMAKE_CXX_FLAGS="$CXX_FLAGS"
    CMAKE_SHARED_LINKER_FLAGS="$LDFLAGS"
    CMAKE_EXE_LINKER_FLAGS="$LDFLAGS"
  )

  pushd "$ORT_DIR" >/dev/null
  BUILD_LOG_FILE="$ABI_BUILD_DIR/build_$ABI.log"
  python3 tools/ci_build/build.py \
    "${COMMON_ARGS[@]}" \
    --cmake_path "$CMAKE_PATH" \
    --cmake_extra_defines "${CMAKE_DEFINES[@]}" \
    >> "$BUILD_LOG_FILE" 2>&1 || { echo "ERROR: ONNX build failed for $ABI. See $BUILD_LOG_FILE" >&2; tail -n 40 "$BUILD_LOG_FILE" >&2 || true; popd >/dev/null; exit 1; }
  popd >/dev/null

  # Locate artifacts
  LIB_CORE="$ABI_BUILD_DIR/Release/libonnxruntime.so"
  LIB_JNI="$ABI_BUILD_DIR/Release/libonnxruntime4j_jni.so"
  [ -f "$LIB_CORE" ] || LIB_CORE="$(find "$ABI_BUILD_DIR" -type f -name 'libonnxruntime.so' -print -quit || true)"
  [ -f "$LIB_JNI"  ] || LIB_JNI="$(find "$ABI_BUILD_DIR" -type f -name 'libonnxruntime4j_jni.so' -print -quit || true)"
  if [ -z "$LIB_CORE" ] || [ -z "$LIB_JNI" ]; then
    echo "ERROR: libonnxruntime(.so) or libonnxruntime4j_jni(.so) not found." >&2
    exit 1
  fi

  # Copy into project
  mkdir -p "$JNI_LIBS_BASE/$ABI"
  cp -f "$LIB_CORE" "$JNI_LIBS_BASE/$ABI/libonnxruntime.so"
  cp -f "$LIB_JNI"  "$JNI_LIBS_BASE/$ABI/libonnxruntime4j_jni.so"

  # Strip (optional)
  if [ -n "${STRIP_BIN:-}" ] && [ -x "$STRIP_BIN" ]; then
    "$STRIP_BIN" --strip-all \
      --remove-section=.comment \
      --remove-section=.note \
      --remove-section=.note.gnu.build-id \
      --remove-section=.note.gnu.property \
      "$JNI_LIBS_BASE/$ABI/libonnxruntime.so" || true
    "$STRIP_BIN" --strip-all \
      --remove-section=.comment \
      --remove-section=.note \
      --remove-section=.note.gnu.build-id \
      --remove-section=.note.gnu.property \
      "$JNI_LIBS_BASE/$ABI/libonnxruntime4j_jni.so" || true
    info "Stripping done."
  fi

  # Copy Java JAR once
  if [ ! -f "$APP_LIBS/onnxruntime-1.24.1.jar" ]; then
    JAR_PATH="$(find "$ORT_DIR/java/build/libs" -type f -name 'onnxruntime.jar' \
      ! -name '*sources*.jar' ! -name '*javadoc*.jar' -print -quit || true)"
    [ -n "$JAR_PATH" ] || { echo "ERROR: onnxruntime JAR not found."; exit 1; }
    if ! jar tf "$JAR_PATH" | grep -q 'ai/onnxruntime/OrtEnvironment.class'; then
      echo "ERROR: JAR missing classes: $JAR_PATH"
      exit 1
    fi
    mkdir -p "$APP_LIBS"
    cp -f "$JAR_PATH" "$APP_LIBS/onnxruntime-1.24.1.jar"
  fi
done

info "Done."
info "JAR: $APP_LIBS/onnxruntime-1.24.1.jar"
for ABI in $ABIS; do
  info "SOs ($ABI): $JNI_LIBS_BASE/$ABI/libonnxruntime.so, libonnxruntime4j_jni.so"
done
