#!/usr/bin/env bash
# Generates paddleocr_v5.required_operators.config from det.onnx + rec.onnx.
#
# The resulting file is consumed by scripts/build_onnxruntime_android.sh via the
# --include_ops_by_config flag of ONNX Runtime's minimal build, in addition to
# (or merged with) the existing DocQuad config.
#
# Usage:
#   scripts/generate_paddleocr_v5_ops_config.sh [OUTPUT_PATH]
#
# Defaults:
#   OUTPUT_PATH = app/src/paddle/assets/paddleocr/v5/paddleocr_v5.required_operators.config
#
# Requirements:
#   * Python 3 with the `onnx` package available (e.g. via repo `venv/`).
#   * det.onnx and rec.onnx present under app/src/paddle/assets/paddleocr/v5/.
#   * ONNX Runtime sources checked out under external/onnxruntime/ (submodule).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODELS_DIR="$REPO_DIR/app/src/paddle/assets/paddleocr/v5"
ORT_TOOL="$REPO_DIR/external/onnxruntime/tools/python/create_reduced_build_config.py"

OUTPUT="${1:-$MODELS_DIR/paddleocr_v5.required_operators.config}"

if [ ! -f "$MODELS_DIR/det.onnx" ] || [ ! -f "$MODELS_DIR/rec.onnx" ]; then
  echo "ERROR: Expected det.onnx and rec.onnx under $MODELS_DIR" >&2
  echo "       Run scripts/convert_paddleocr_v5.sh first." >&2
  exit 1
fi

if [ ! -f "$ORT_TOOL" ]; then
  echo "ERROR: ORT helper not found: $ORT_TOOL" >&2
  echo "       Did you initialise the external/onnxruntime submodule?" >&2
  exit 1
fi

# Pick a Python with `onnx` available.  Prefer the repo-local venv if present.
PYTHON_BIN="${PYTHON_BIN:-}"
if [ -z "$PYTHON_BIN" ]; then
  if [ -x "$REPO_DIR/venv/bin/python" ]; then
    PYTHON_BIN="$REPO_DIR/venv/bin/python"
  elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
  else
    PYTHON_BIN="python"
  fi
fi

if ! "$PYTHON_BIN" -c "import onnx" >/dev/null 2>&1; then
  echo "ERROR: Python interpreter '$PYTHON_BIN' has no 'onnx' package." >&2
  echo "       Activate the repo venv or run: $PYTHON_BIN -m pip install onnx" >&2
  exit 1
fi

# Stage det.onnx + rec.onnx in a clean tmpdir so the ORT tool only sees those
# two models (it scans the directory recursively).  We use symlinks so this is
# free even for large model files.
STAGE_DIR="$(mktemp -d -t paddleocr_v5_ops.XXXXXX)"
trap 'rm -rf "$STAGE_DIR"' EXIT

ln -s "$MODELS_DIR/det.onnx" "$STAGE_DIR/det.onnx"
ln -s "$MODELS_DIR/rec.onnx" "$STAGE_DIR/rec.onnx"

mkdir -p "$(dirname "$OUTPUT")"

echo "Generating reduced-ops config from:" >&2
echo "  - $MODELS_DIR/det.onnx" >&2
echo "  - $MODELS_DIR/rec.onnx" >&2
echo "Output: $OUTPUT" >&2

"$PYTHON_BIN" "$ORT_TOOL" --format ONNX "$STAGE_DIR" "$OUTPUT"

# The tool emits "# - <staged path>" comments; rewrite them so the config is
# reproducible regardless of the temp-dir name.
TMP_OUT="$(mktemp -t paddleocr_v5_ops_rewrite.XXXXXX)"
{
  echo "# Generated by scripts/generate_paddleocr_v5_ops_config.sh"
  echo "# Source models (relative to repo root):"
  echo "#   - app/src/paddle/assets/paddleocr/v5/det.onnx"
  echo "#   - app/src/paddle/assets/paddleocr/v5/rec.onnx"
  # Drop the original "# Generated from..." preamble + per-file comments, keep
  # only the actual "domain;opset;ops" lines.
  awk 'NF && $0 !~ /^#/ { print }' "$OUTPUT"
} > "$TMP_OUT"
mv "$TMP_OUT" "$OUTPUT"

echo "Wrote $(wc -l < "$OUTPUT" | tr -d ' ') entries to $OUTPUT" >&2
