#!/usr/bin/env bash
# Generates paddleocr_v5.required_operators.config from det.onnx + all
# PP-OCRv5 mobile recognition ONNX models.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODELS_DIR="$REPO_DIR/paddle-spike/onnx/"
ORT_TOOL="$REPO_DIR/external/onnxruntime/tools/python/create_reduced_build_config.py"

OUTPUT="${1:-$MODELS_DIR/paddleocr_v5.required_operators.config}"

if [ ! -f "$MODELS_DIR/det.onnx" ]; then
  echo "ERROR: Expected det.onnx under $MODELS_DIR" >&2
  exit 1
fi

if [ ! -f "$ORT_TOOL" ]; then
  echo "ERROR: ORT helper not found: $ORT_TOOL" >&2
  echo "       Did you initialise the external/onnxruntime submodule?" >&2
  exit 1
fi

PYTHON_BIN="${PYTHON_BIN:-}"
if [ -z "$PYTHON_BIN" ]; then
  if [ -x "$REPO_DIR/venv/bin/python" ]; then
    PYTHON_BIN="$REPO_DIR/venv/bin/python"
  elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
  else
    PYTHON_BIN="python"
  fi
fi

if ! "$PYTHON_BIN" -c "import onnx" >/dev/null 2>&1; then
  echo "ERROR: Python interpreter '$PYTHON_BIN' has no 'onnx' package." >&2
  echo "       Activate the repo venv or run: $PYTHON_BIN -m pip install onnx" >&2
  exit 1
fi

REC_MODELS=()
while IFS= read -r f; do
  REC_MODELS+=("$f")
done < <(
  find "$MODELS_DIR" -maxdepth 1 -type f -name "*PP-OCRv5_mobile_rec.onnx" | sort
)

if [ "${#REC_MODELS[@]}" -eq 0 ]; then
  echo "ERROR: No PP-OCRv5 mobile rec ONNX models found under $MODELS_DIR" >&2
  echo "       Expected files like en_PP-OCRv5_mobile_rec.onnx or PP-OCRv5_mobile_rec.onnx" >&2
  exit 1
fi

STAGE_DIR="$(mktemp -d -t paddleocr_v5_ops.XXXXXX)"
trap 'rm -rf "$STAGE_DIR"' EXIT

ln -s "$MODELS_DIR/det.onnx" "$STAGE_DIR/det.onnx"

for model in "${REC_MODELS[@]}"; do
  ln -s "$model" "$STAGE_DIR/$(basename "$model")"
done

mkdir -p "$(dirname "$OUTPUT")"

echo "Generating reduced-ops config from:" >&2
echo "  - $MODELS_DIR/det.onnx" >&2
for model in "${REC_MODELS[@]}"; do
  echo "  - $model" >&2
done
echo "Output: $OUTPUT" >&2

"$PYTHON_BIN" "$ORT_TOOL" --format ONNX "$STAGE_DIR" "$OUTPUT"

TMP_OUT="$(mktemp -t paddleocr_v5_ops_rewrite.XXXXXX)"
{
  echo "# Generated by scripts/generate_paddleocr_v5_ops_config.sh"
  echo "# Source models (relative to repo root):"
  echo "#   - app/src/paddle/assets/paddleocr/v5/det.onnx"

  for model in "${REC_MODELS[@]}"; do
    rel="${model#$REPO_DIR/}"
    echo "#   - $rel"
  done

  awk 'NF && $0 !~ /^#/ { print }' "$OUTPUT"
} > "$TMP_OUT"

mv "$TMP_OUT" "$OUTPUT"

echo "Wrote $(awk 'NF && $0 !~ /^#/ { c++ } END { print c+0 }' "$OUTPUT") operator config lines to $OUTPUT" >&2